greeter:
  ribbon:
    listOfServers: localhost:8080,localhost:8081
    ServerListRefreshInterval: 2000

ribbon:
  eureka:
    enabled: false

spring:
  application:
    name: greeter
  main:
    banner-mode: off

server:
  port: 9090

