spring:
  application:
    name: rest-service
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
server:
  port: 8080

